### ISSUE TITLE
fpdi_bridge Class check error

### ISSUE THREAD

**Issue by kakajansh** [mark9000/FPDI#8]
I am not sure but is there an error ?

```
if (!class_exists('TCPDF', false)) {
    /**
     * Class fpdi_bridge
     */
    class fpdi_bridge extends FPDF
    {
        // empty body
    }

} else {
```

I think it should be `class_exists('TCPDF', false)`or `!class_exists('TCPDF', true)`

**Comment by Nenillo** [comment]
I think it should be class_exists('TCPDF', true), otherwise it won't be able to find autoloaded TCPDF

**Comment by mark9000** [comment]
It is intended that autoload is not used here. You should be able to choose manually which lib (fpdf or tcpdf) you want to use. For example in an application the user can choose in the settings the lib he wants to use.

**Comment by Nenillo** [comment]
But how do you choose it? Manually calling require with the lib you want?

**Comment by mark9000** [comment]
Yes. It is not a very nice solution i know.

**Comment by nmathon** [comment]
It should be 

```
    if (!class_exists('TCPDF', true)) { 
```

to works with PCR-0 loaded TCPDF
Autoload is needed with some frameworks like Symfony

**Comment by mark9000** [comment]
Since a few month there is an official repo. Please check https://github.com/Setasign/FPDI.
